### ISSUE TITLE
Accounts Report Printing

### ISSUE THREAD

**Issue by siabhinav** [alurakhil24/TempleStarter#106]
Entire Page is not printing we see the scroll bar
Need to have word wrap for data in the cells below.
the headers need to be also wrapped
 Phone    Cheque    Created
Number      No           Date 

![image](https://user-images.githubusercontent.com/5601909/44958974-66407e00-af05-11e8-9916-e9c98e3b4fd0.png)

**Comment by SravanKumarL** [comment]
Fixed in latest build
