### ISSUE TITLE
User Management Report

### ISSUE THREAD

**Issue by siabhinav** [alurakhil24/TempleStarter#107]
When I try to pick a previous day of any other day report we are getting the records of the said date but the header is not getting updated it is showing only current date on top. 
![image](https://user-images.githubusercontent.com/5601909/44960160-3babf080-af18-11e8-9aa4-2e5f531a339c.png)
and another I did transaction today i.e. 3-9-2018 at 1:26 am but the record is not seen in management report of today but its added under yesterdays records
![image](https://user-images.githubusercontent.com/5601909/44960177-90e80200-af18-11e8-9a30-526e36a51b98.png)
u can see the amount difference in the above image.
- When I selected the current date it shows no records 
![image](https://user-images.githubusercontent.com/5601909/44960196-c5f45480-af18-11e8-9e0b-0f8e2f2b8564.png)

**Comment by alurakhil24** [comment]
Issue not reproducible. Please reopen it if it is reproduced and put up the workflow. For testing, change the system date and time to see the issue.
