### ISSUE TITLE
Accounts Report Preview 

### ISSUE THREAD

**Issue by siabhinav** [alurakhil24/TempleStarter#108]
As said in the previous issue #107  accounts reports is also not showing the current day details 
![image](https://user-images.githubusercontent.com/5601909/44960222-1c619300-af19-11e8-9b0d-52a25fcc6f45.png)
Do we have any DB refresh or issue at this time?

**Comment by alurakhil24** [comment]
The issue is not reproducible . Please change the system date and check it once.If it is reproducible. Please re-open it.
