### ISSUE TITLE
Proper Case

### ISSUE THREAD

**Issue by siabhinav** [alurakhil24/TempleStarter#95]
When Trying to add new Pooja details in Poojas tab. We try to add Pooja name in Proper-case but its getting converted to lowercase. 
![image](https://user-images.githubusercontent.com/5601909/44671483-3bf14b00-aa43-11e8-8bca-f5f79f841da6.png)

**Comment by alurakhil24** [comment]
This is now fixed in the latest build. Reopen if it still exists
