### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by siabhinav** [alurakhil24/TempleStarter#96]
While printing a single pooja ticket i observed that its taking 2 sheets  but we have only 1 sheet to be printed .

Another one we are using 2 printers one for Tickets and another for management,pooja audit reports i.e. A4 size.So need to align the printing properties accordingly.

**Comment by alurakhil24** [comment]
But print will come on only one page. I tested this and this is working. Please reopen if this is not working on your end. It will show preview in two pages but printing in one receipt. Call if any doubt

**Comment by siabhinav** [comment]
Sure
