### ISSUE TITLE
Management Report

### ISSUE THREAD

**Issue by siabhinav** [alurakhil24/TempleStarter#99]
Not able to generate mgnt report when logged in as a user.
![image](https://user-images.githubusercontent.com/5601909/44672798-28e07a00-aa47-11e8-9866-bebbb84cef3f.png)
But when logged in as a admin able to generate the same.
![image](https://user-images.githubusercontent.com/5601909/44672908-8aa0e400-aa47-11e8-8602-19cad1921ed5.png)

**Comment by alurakhil24** [comment]
Able to generate it in the latest build. Re open if reproduced. I tested it on EUB
